type UserType = {
    id:number,
    username:string,
    userAccount:string,
    avatarUrl?:string,
    userPassword:string,
    gender:number,
    telephone:string,
    email :string,
    userStatus:number,
    createTime:Date,
    planetCode:string,
    tags:string[],
    userRole:number,
};